### ISSUE TITLE
Group Homework assignment 1

### ISSUE THREAD

**Issue by cit280superepicness** [cit352/documentation#3]
Instructions: Study Chapter 2 and 3 of Text and see corresponding lecture slides. Next study chapter 5 and 6 of PMP book uploaded on Moodle. Apply the knowledge gained to perform following:
a- Finalize the scope management plan of your project. (20 points)
 b- Perform SWOT Analysis of your project using Visible Analyst CASE tool (see chapter 2 of text) (15 points)
c- Google "Sample business case" to review different business case. Pick one that is closer to your project. your task is to writeup business case of your project. (10 points)
c- Higher management has asked you to complete Preliminary investigation of your project. your task is to complete preliminary investigation of your project ( see chapter 2 of your text). (30 points)
d- Draw Giant chart , Network diagram, critical path and complete schedule of your project  using Microsoft project (5+5+5+10=25 points)

**Comment by petekal1323** [comment]
Lets do this all together when we meet up today :)

BTW is anyone else having trouble opening the PMP book by rita?

**Comment by cit280superepicness** [comment]
I don't know if you included the other group members in this or not (I
don't see them unless you put them in a bcc).

I didn't have much problem opening the PMP book. I tried top open it in my
browser but it took too long to load so I just downloaded it via the link
on Moodle and was able to get to it without a problem that way.
